// <auto-generated />
using FlowerSellerTgBot.Model.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowerSellerTgBot.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241217174240_InitMigr")]
    partial class InitMigr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowerSellerTgBot.Model.DataBase.DbObjects.CartObject", b =>
                {
                    b.Property<string>("ChatId")
                        .HasColumnType("text");

                    b.Property<string>("CartKey")
                        .HasColumnType("text");

                    b.HasKey("ChatId");

                    b.ToTable("cartObjects");
                });

            modelBuilder.Entity("FlowerSellerTgBot.Model.DataBase.DbObjects.CategoryObject", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("NameOf")
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("categoryObjects");
                });

            modelBuilder.Entity("FlowerSellerTgBot.Model.DataBase.DbObjects.PhotoObject", b =>
                {
                    b.Property<string>("FileId")
                        .HasColumnType("text");

                    b.Property<string>("PhotoKey")
                        .HasColumnType("text");

                    b.HasKey("FileId");

                    b.ToTable("photoObjects");
                });

            modelBuilder.Entity("FlowerSellerTgBot.Model.DataBase.DbObjects.ProductCartObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cartkey")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("cartproductObjects");
                });

            modelBuilder.Entity("FlowerSellerTgBot.Model.DataBase.DbObjects.ProductObject", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("MediaKey")
                        .HasColumnType("text");

                    b.Property<string>("Price")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.ToTable("productObjects");
                });

            modelBuilder.Entity("FlowerSellerTgBot.Model.DataBase.DbObjects.SellerObject", b =>
                {
                    b.Property<int>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SellerId"));

                    b.Property<string>("ChatId")
                        .HasColumnType("text");

                    b.HasKey("SellerId");

                    b.ToTable("sellerObjects");
                });

            modelBuilder.Entity("FlowerSellerTgBot.Model.DataBase.DbObjects.VideoObject", b =>
                {
                    b.Property<string>("FileId")
                        .HasColumnType("text");

                    b.Property<string>("VideoKey")
                        .HasColumnType("text");

                    b.HasKey("FileId");

                    b.ToTable("videoObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
